# Go through near-dupes.txt and dupe-skip.txt and eliminate common report
# IDs.  What remains in near-dupes.txt are those near dupe IDs that should be
# eliminated.

# near-dupes.txt generated by:
# grep "near dupe" gdas_dump_06.o1516940.p-cor-air | sort | uniq > near-dupes.txt
# dupe-skip.txt generated by:
# grep "dupe; skip" gdas_dump_06.o1516940.p-cor-air | sort | uniq > exact-dupes.txt

wkdir=/meso/save/$USER/svnwkspc/melchior/tac2bufr_monitor
nearfl=$wkdir/near-dupes.txt.p-cor-air
skipfl=$wkdir/exact-dupes.txt.p-cor-air

cnt=0
cat $nearfl | while read line
do
  rptindex=$(echo $line | cut -f2 -d"-") 
  test=$(grep -o ${rptindex}$ $skipfl)
  if [ -z $test ]; then
#   echo "$rptindex not tossed!"
    cnt=$((cnt+1))
   echo $cnt
  fi 
done
echo $cnt
