# .bash_profile

# Get the aliases and functions
. /usrx/local/Modules/default/init/bash
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin

export PATH
